services:
  backpackregistrycouponspostgres:
    image: 'postgres:11.5'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lists
    ports:
      - '5432:5432'
  zookeeper:
    image: 'wurstmeister/zookeeper:3.4.6'
    ports:
      - '2181:2181'
  kafka:
    image: 'wurstmeister/kafka:2.12-2.3.0'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISE_HOST_PORT=9092
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - 'KAFKA_CREATE_TOPICS=lists-msg-bus:1:1,lists-dlq:1:1'
pipeline:
  restore_cache:
    image: 'docker.target.com/drone/drone-s3-cache:2'
    pull: true
    restore: true
    secrets:
      - cache_s3_server
      - cache_s3_access_key
      - cache_s3_secret_key
      - cache_s3_ca_cert

  publish-config-backpack-registry-coupons-dev:
    when:
      event: [push]
      branch: master
    image: 'docker.target.com/app/lists/alpine-bash-curl-ssl:1.0.5'
    environment:
      CICD_MODE: 'true'
    secrets:
      - TAP_API_TOKEN
      - backpack_registry_coupons_app_private_key_dev
      - backpack_registry_coupons_consumer_app_private_key_dev
    commands:
      - 'tap_api_token=$TAP_API_TOKEN app_private_key=$BACKPACK_REGISTRY_COUPONS_APP_PRIVATE_KEY_DEV ./backpack-registry-coupons-app/scripts/config_deploy_manager.sh conf.dev.0.0'
      - 'tap_api_token=$TAP_API_TOKEN app_private_key=$BACKPACK_REGISTRY_COUPONS_CONSUMER_APP_PRIVATE_KEY_DEV ./backpack-registry-coupons-consumer-app/scripts/config_deploy_manager.sh conf.dev.0.0'

  publish-config-backpack-registry-coupons-stage:
    when:
      event: tag
      ref: 'refs/tags/conf.stage.backpackregistrycoupons.*'
      branch: master
    image: 'docker.target.com/app/lists/alpine-bash-curl-ssl:1.0.5'
    environment:
      CICD_MODE: 'true'
    secrets:
      - TAP_API_TOKEN
      - backpack_registry_coupons_app_private_key_stage
      - backpack_registry_coupons_consumer_app_private_key_stage
    commands:
      - 'tap_api_token=$TAP_API_TOKEN app_private_key=$BACKPACK_REGISTRY_COUPONS_APP_PRIVATE_KEY_STAGE ./backpack-registry-coupons-app/scripts/config_deploy_manager.sh ${DRONE_TAG}'
      - 'tap_api_token=$TAP_API_TOKEN app_private_key=$BACKPACK_REGISTRY_COUPONS_CONSUMER_APP_PRIVATE_KEY_STAGE ./backpack-registry-coupons-consumer-app/scripts/config_deploy_manager.sh ${DRONE_TAG}'

  publish-config-backpack-registry-coupons-prod:
    when:
      event: tag
      ref: 'refs/tags/conf.prod.backpackregistrycoupons.*'
      branch: master
    image: 'docker.target.com/app/lists/alpine-bash-curl-ssl:1.0.5'
    environment:
      CICD_MODE: 'true'
    secrets:
      - TAP_API_TOKEN
      - backpack_registry_coupons_app_private_key_prod
      - backpack_registry_coupons_consumer_app_private_key_prod
    commands:
      - 'tap_api_token=$TAP_API_TOKEN app_private_key=$BACKPACK_REGISTRY_COUPONS_APP_PRIVATE_KEY_PROD ./backpack-registry-coupons-app/scripts/config_deploy_manager.sh ${DRONE_TAG}'
      - 'tap_api_token=$TAP_API_TOKEN app_private_key=$BACKPACK_REGISTRY_COUPONS_CONSUMER_APP_PRIVATE_KEY_PROD ./backpack-registry-coupons-consumer-app/scripts/config_deploy_manager.sh ${DRONE_TAG}'

  build:
    when:
      event: [pull_request, push, tag]
    image: 'docker.target.com/tap/alpine-openjdk11-build:latest'
    environment:
      JAVA_TOOL_OPTIONS: '-Xmx4000M'
      GRADLE_USER_HOME: .gradle
      GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1 -Dorg.gradle.parallel=false'
      JDBC_URL: 'jdbc:postgresql://backpackregistrycouponspostgres:5432/lists'
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
    commands:
      - './gradlew build distTar'

  rebuild_cache:
    image: 'docker.target.com/drone/drone-s3-cache:2'
    rebuild: true
    secrets:
      - cache_s3_server
      - cache_s3_access_key
      - cache_s3_secret_key
      - cache_s3_ca_cert
    mount:
      - .gradle

  flush_cache:
    image: 'docker.target.com/drone/drone-s3-cache:2'
    secrets:
      - cache_s3_server
      - cache_s3_access_key
      - cache_s3_secret_key
      - cache_s3_ca_cert
    flush: true
    flush_age: 14

  publish-docker-backpackregistrycoupons-app-dev:
    image: plugins/docker
    group: devimggroup
    registry: docker.target.com
    repo: docker.target.com/app/backpack-registry-coupons/backpack-registry-coupons-app
    dockerfile: ./backpack-registry-coupons-app/Dockerfile
    tags:
      - 'b${DRONE_BUILD_NUMBER}-${DRONE_COMMIT:0:8}'
      - latest
    when:
      event: [push]
      branch: master
    secrets:
      - {source: artifactory_username, target: plugin_username}
      - {source: artifactory_password, target: plugin_password}

  publish-docker-backpack-registry-coupons-app-stage:
    image: 'plugins/docker:latest'
    group: stgimggroup
    registry: docker.target.com
    repo: docker.target.com/app/backpack-registry-coupons/backpack-registry-coupons-app
    dockerfile: ./backpack-registry-coupons-app/Dockerfile
    tags: 'rc.${DRONE_TAG:24}'
    when:
      event: tag
      branch: master
      ref: 'refs/tags/conf.stage.backpackregistrycoupons.*'
    secrets:
      - {source: artifactory_username, target: plugin_username}
      - {source: artifactory_password, target: plugin_password}

  publish-docker-backpack-registry-coupons-app-prod:
    image: 'docker.target.com/drone/docker-promotion:1'
    source_repo: docker.target.com/app/backpack-registry-coupons/backpack-registry-coupons-app
    source_tag: 'rc.${DRONE_TAG:23}'
    target_repo: docker.target.com/app/backpack-registry-coupons/backpack-registry-coupons-app
    target_tags: 'prod.${DRONE_TAG:23}'
    when:
      event: tag
      branch: master
      ref: 'refs/tags/conf.prod.backpackregistrycoupons.*'
    secrets:
      - {source: artifactory_username, target: registry_username}
      - {source: artifactory_password, target: registry_password}

  publish-docker-backpack-registry-coupons-consumer-app-dev:
    image: plugins/docker
    group: devimggroup
    registry: docker.target.com
    repo: docker.target.com/app/backpack-registry-coupons/backpack-registry-coupons-consumer-app
    dockerfile: ./backpack-registry-coupons-consumer-app/Dockerfile
    tags:
      - 'b${DRONE_BUILD_NUMBER}-${DRONE_COMMIT:0:8}'
      - latest
    when:
      event: [push]
      branch: master
    secrets:
      - {source: artifactory_username, target: plugin_username}
      - {source: artifactory_password, target: plugin_password}

  publish-docker-backpack-registry-coupons-consumer-app-stage:
    image: 'plugins/docker:latest'
    group: stgimggroup
    registry: docker.target.com
    repo: docker.target.com/app/backpack-registry-coupons/backpack-registry-coupons-consumer-app
    dockerfile: ./backpack-registry-coupons-consumer-app/Dockerfile
    tags: 'rc.${DRONE_TAG:24}'
    when:
      event: tag
      branch: master
      ref: 'refs/tags/conf.stage.backpackregistrycoupons.*'
    secrets:
      - {source: artifactory_username, target: plugin_username}
      - {source: artifactory_password, target: plugin_password}

  publish-docker-backpack-registry-coupons-consumer-app-prod:
    image: 'docker.target.com/drone/docker-promotion:1'
    source_repo: docker.target.com/app/backpack-registry-coupons/backpack-registry-coupons-consumer-app
    source_tag: 'rc.${DRONE_TAG:23}'
    target_repo: docker.target.com/app/backpack-registry-coupons/backpack-registry-coupons-consumer-app
    target_tags: 'prod.${DRONE_TAG:23}'
    when:
      event: tag
      branch: master
      ref: 'refs/tags/conf.prod.backpackregistrycoupons.*'
    secrets:
      - {source: artifactory_username, target: registry_username}
      - {source: artifactory_password, target: registry_password}

secrets:
  cache_s3_server:
    path: secret/shared/drone/prod-secrets/cache_s3_server
  cache_s3_access_key:
    path: secret/shared/drone/prod-secrets/cache_s3_access_key
  cache_s3_secret_key:
    path: secret/shared/drone/prod-secrets/cache_s3_secret_key
  cache_s3_ca_cert:
    path: secret/shared/drone/prod-secrets/cache_s3_ca_cert
  backpack_registry_coupons_app_private_key_dev:
    path: secret/repo/Registry-Modernization/backpack-registry-coupons/backpackregistrycoupons-privkey-dev
  backpack_registry_coupons_app_private_key_stage:
    path: secret/repo/Registry-Modernization/backpack-registry-coupons/backpackregistrycoupons-privkey-stage
  backpack_registry_coupons_app_private_key_prod:
    path: secret/repo/Registry-Modernization/backpack-registry-coupons/backpackregistrycoupons-privkey-prod
  backpack_registry_coupons_consumer_app_private_key_dev:
    path: secret/repo/Registry-Modernization/backpack-registry-coupons/backpackregistrycouponsconsumer-privkey-dev
  backpack_registry_coupons_consumer_app_private_key_stage:
    path: secret/repo/Registry-Modernization/backpack-registry-coupons/backpackregistrycouponsconsumer-privkey-stage
  backpack_registry_coupons_consumer_app_private_key_prod:
    path: secret/repo/Registry-Modernization/backpack-registry-coupons/backpack-registry-couponsconsumer-privkey-prod
