version: "1"
services:
  - name: backpackregistrycouponspostgres
    image: 'postgres:11.5'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lists
    ports:
      - '5432:5432'
  - name: zookeeper
    image: 'wurstmeister/zookeeper:3.4.6'
    ports:
      - '2181:2181'
  - name: kafka
    image: 'wurstmeister/kafka:2.12-2.3.0'
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISE_HOST_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: lists-msg-bus:1:1,lists-dlq:1:1

steps:
  - name: restore_cache
    image: docker.target.com/vela-plugins/s3-cache:v0.5.1-1
    secrets: [ cache_s3_access_key, cache_s3_secret_key, cache_s3_server ]
    parameters:
      action: restore

  - name: publish-config-backpack-registry-coupons-dev
    ruleset:
      event: [ push ]
      branch: vela
    image: 'docker.target.com/app/lists/alpine-bash-curl-ssl:1.0.5'
    environment:
      CICD_MODE: 'true'
    secrets:
      - TAP_API_TOKEN
      - backpack_registry_coupons_app_private_key_dev
    commands:
      - export BACKPACK_REGISTRY_COUPONS_APP_PRIVATE_KEY_DEV=$(cat /vela/secrets/backpack_registry_coupons_app_private_key_dev/privkey)
      - tap_api_token=$TAP_API_TOKEN app_private_key=$BACKPACK_REGISTRY_COUPONS_APP_PRIVATE_KEY_DEV ./backpack-registry-coupons-app/scripts/config_deploy_manager.sh conf.dev.0.0

  - name: build
    image: 'docker.target.com/tap/alpine-openjdk11-build:latest'
    ruleset:
      event: [ pull_request, push, tag ]
    environment:
      JAVA_TOOL_OPTIONS: '-Xmx4000M'
      GRADLE_USER_HOME: .gradle
      GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=1 -Dorg.gradle.parallel=false'
      JDBC_URL: 'jdbc:postgresql://backpackregistrycouponspostgres:5432/lists'
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
    commands:
      - 'mkdir -p masterspec'
      - 'git clone https://git.target.com/Registry-Modernization/backpack-registry-coupons --branch master --single-branch masterspec'
      - 'export GIT_MASTER_SPEC_PATH=`pwd`/masterspec'
      - './gradlew build distTar'

  - name: rebuild_cache
    image: docker.target.com/vela-plugins/s3-cache:2
    secrets: [ cache_s3_access_key, cache_s3_secret_key, cache_s3_server ]
    parameters:
      action: rebuild
      mount:
        - .gradle

  - name: flush_cache
    image: docker.target.com/vela-plugins/s3-cache:2
    secrets: [ cache_s3_access_key, cache_s3_secret_key, cache_s3_server ]
    parameters:
      action: flush
      flush_age: 14

  - name: publish-docker-backpackregistrycoupons-app-dev
    image: docker.target.com/vela-plugins/kaniko:v0.6.0-1
    pull: always
    parameters:
      registry: docker.target.com
      repo: docker.target.com/app/backpack-registry-coupons/backpack-registry-coupons-app
      dockerfile: ./backpack-registry-coupons-app/Dockerfile
      tags:
        - 'b${BUILD_NUMBER}-${BUILD_COMMIT:0:8}'
        - latest
    ruleset:
      event: [ push ]
      branch: vela
    environment:
      CICD_MODE: 'true'
    secrets: [ docker_username, docker_password ]

secrets:
  - name: cache_s3_server
    key: vela/prod-secrets/cache_s3_server
    engine: native
    type: shared
  - name: cache_s3_access_key
    key: vela/prod-secrets/cache_s3_access_key
    engine: native
    type: shared
  - name: cache_s3_secret_key
    key: vela/prod-secrets/cache_s3_secret_key
    engine: native
    type: shared
  - name: TAP_API_TOKEN
    key: Registry-Modernization/TAP_API_TOKEN
    engine: native
    type: org
  - name: vault_username
    key: Registry-Modernization/vault_username
    engine: native
    type: org
  - name: vault_password
    key: Registry-Modernization/vault_password
    engine: native
    type: org
  - name: docker_username
    key: Registry-Modernization/docker_username
    engine: native
    type: org
  - name: docker_password
    key: Registry-Modernization/docker_password
    engine: native
    type: org
  - origin:
      name: vault
      image: docker.target.com/vela-secrets/vault:latest
      pull: always
      secrets: [ vault_username, vault_password ]
      parameters:
        log_level: debug
        items:
          - source: secret/registries-modernization/dev/backpack-registry-coupons/backpackregistrycoupons-privkey
            path: backpack_registry_coupons_app_private_key_dev
