micronaut:
  application:
    name: backpack-registry-coupons-app
  server:
    host: ${backpack-registry-coupons-app-host:localhost}
    port: 8081
    idle-timeout: 2000ms
    netty:
      max-header-size: 16384 # Handling RequestTooLarge headers - Default value (8192)
    multipart:
      max-file-size: 100mb

  http:
    client.connect-ttl: 30m
    client.read-timeout: 5000ms
    services:
      permissions-api:
        urls:
          - "https://registriespermissions.dev.target.com"
        connect-timeout: 300ms
        read-timeout: 300ms
        pool:
          enabled: true
          max-connections: 128
          max-pending-acquires: 50

  metrics:
    binders:
      web:
        enabled: false # we are using our own binder via our custom micronaut-metrics lib

filter:
  server:
    order:
      mdc-filter: 50
      onbehalf-filter: 51
      lists-brave-tracing-server-filter: 100
      list-authorization-filter: 200
      sanitizing-filter: 300
  client:
    order:
      lists-brave-tracing-client-filter: 900
      resilience-client-filter: 800
      oauth-filter: 701
      oauth-key-filter: 700

components:
  apispec:
    filepath: apispec/backpack-registry-coupons-v1.yml
  errocodes:
    classes:
      - com.tgt.lists.common.components.exception.BaseErrorCodes #Haven't defined app specific error codes yet
  server:
    onbehalf-filter:
      enabled: true
      gsp-validation-base-url: "https://backpackregistrycoupons.dev.target.com"
      team-email-ids:
        - Indrakumar.Thimmaiah@target.com
        - Kiran.Shivalingaiah@target.com
        - Parthasarathy.Hd@target.com
      approver-email-ids:
        - Indrakumar.Thimmaiah@target.com
    list-authorization-filter:
      enabled: true
      base-uri: /registries_coupons/v1
      internal-ad-group: APP-BACKPACK-REGISTRY
    ad-group-permissions:
      get-access:
        permissions[0]:
          groups:
            - APP-BACKPACK-REGISTRY
          urls:
            - /registries_coupons/v1/*
      post-access:
        permissions[0]:
          groups:
            - APP-BACKPACK-REGISTRY
          urls:
            - /uploads
    id2-custom-scopes:
      names:
        - axiom.user
        - axiom.admin
        - axiom.leader
      profile-header: member_id
    sanitizing-filter:
      enabled: false
    registry-channel-subchannel-filter:
      enabled: false

msgbus:
  source: backpack-registry-coupons
  dlq-source: backpack-registry-coupons-app-dlq
  kafka:
    consumer:
      enabled: false
    producer:
      enabled: true
      client-id: backpack-registry-coupons-bus-dev-producer
    dlqconsumer:
      enabled: false
    dlqproducer:
      enabled: true
      client-id: backpack-registry-coupons-dlq-dev-producer
    topic: registry-internal-data-bus-dev
    consumer-group: backpack-registry-coupons-bus-dev
    consumer-batch-size: 10
    dlq-topic: registry-internal-data-bus-dev-dlq
    dlq-consumer-group: backpack-registry-coupons-bus-dev-dlq
    dlq-event-retry-interval-secs: 1
    dlq-max-event-retry-count: 2
    dlq-consumer-batch-size: 10

notification:
  source: backpack-registry-coupons
  dlq-source: backpack-registry-coupons-app-dlq
  enabled: true

kafka:
  bootstrap:
    servers: kafka-ttc-app.dev.target.com:9093
  ssl:
    endpoint.identification.algorithm: ""# disable karka broker cert's hostname verification
    keystore:
      location: /lists-bus-keystore.jks
      password: ${kafka-secret.keystore-password}
    truststore:
      location: /client-truststore.jks
      password: ${kafka-secret.truststore-password}
      type: PKCS12
  security:
    protocol: ssl
  consumers:
    backpack-registry-coupons-bus-dev:
      key:
        deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value:
        deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    backpack-registry-coupons-bus-dev-dlq:
      key:
        deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value:
        deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  producers:
    # default is a Jackson based JSON serializer for key/value
    backpack-registry-coupons-bus-dev-producer:
      key:
        serializer: org.apache.kafka.common.serialization.StringSerializer
      value:
        serializer: com.tgt.lists.msgbus.ListsJsonSerde
      compression:
        type: zstd
      retries: 3
      retry:
        backoff:
          ms: 1000
      max:
        in:
          flight:
            requests:
              per:
                connection: 1
        block:
          ms: 2000
    notification-tracer-producer:
      key:
        serializer: org.apache.kafka.common.serialization.StringSerializer
      value:
        serializer: com.tgt.lists.msgbus.ListsJsonSerde
      compression:
        type: zstd
      retries: 3
      retry:
        backoff:
          ms: 1000
      max:
        in:
          flight:
            requests:
              per:
                connection: 1
        block:
          ms: 2000
    backpack-registry-coupons-dlq-dev-producer:
      key:
        serializer: org.apache.kafka.common.serialization.StringSerializer
      value:
        serializer: com.tgt.lists.msgbus.ListsJsonSerde
      compression:
        type: zstd
      retries: 3
      retry:
        backoff:
          ms: 1000
      max:
        in:
          flight:
            requests:
              per:
                connection: 1
        block:
          ms: 2000

postgres:
  max-db-pool-size: 5
  min-db-pool-size: 1
