version: 2
server:
  listen_address: localhost:8080
environment: prod
health:
  proxy:
   enabled: true
   path: /proxyhealth
api_name: backpack_registrycoupons-v1
metrics:
  push: true
handlers:
  key_validation:
    environment: PROD
  auth:
    anonymous_routes:
      - GET: /health
      - GET: /apispec

    strategies:
      gsp:
          - routes_by_scope:
              ecom.high:
                - GET: /:*
                - POST: /:*
                - PUT: /:*
                - DELETE: /:*
              ecom.low:
                - GET: /:*
                - POST: /:*
                - PUT: /:*
                - DELETE: /:*
              ecom.med:
                - GET: /:*
                - POST: /:*
                - PUT: /:*
                - DELETE: /:*
              ecom.none:
                - GET: /:*
                - POST: /:*
                - PUT: /:*
                - DELETE: /:*
            routes_by_asl:
              H:
                - GET: /:*
                - POST: /:*
                - PUT: /:*
                - DELETE: /:*
              L:
                - GET: /:*
                - POST: /:*
                - PUT: /:*
                - DELETE: /:*
              M:
                - GET: /:*
                - POST: /:*
                - PUT: /:*
                - DELETE: /:*

      id2:
          - routes_by_scope:
              axiom.user:
                - GET: /:*
              axiom.admin:
                - GET: /:*
                - POST: /:*
                - PUT: /:*
                - DELETE: /:*
              axiom.leader:
                - GET: /:*
                - POST: /:*
                - PUT: /:*
                - DELETE: /:*
            routes_by_aal:
              1:
                - GET: /:*
                - POST: /:*
                - PUT: /:*
                - DELETE: /:*
  cors:
    whitelist:
      - https://editor.swagger.io
    allow_any_target_domain: true
    allow_credentials: true
    allow_any_origin: true
    allowed_headers:
      - authorization
      - member_id
      - profile_id
      - X-AUTH-NAME
      - X-AUTH-ID
      - X-API-KEY
      - key
      - Origin
      - Content-Type
      - accept
      - accept-encoding
      - accept-language
      - origin
      - referer
      - sec-ch-ua
      - sec-ch-ua-mobile
      - sec-fetch-dest
      - sec-fetch-mode
      - sec-fetch-site
      - user-agent
      - cache-control
      - pragma
